# Generated by Django 3.0.7 on 2022-01-03 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boat_title', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District Of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField(choices=[(1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], verbose_name='year')),
                ('condition', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('boat_class', models.CharField(max_length=100)),
                ('length', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=100)),
                ('hull_material', models.CharField(max_length=100)),
                ('boat_location', models.CharField(max_length=100)),
                ('tax_status', models.CharField(max_length=100)),
                ('loa', models.CharField(max_length=100)),
                ('beam', models.CharField(max_length=100)),
                ('max_draft', models.CharField(max_length=100)),
                ('min_draft', models.CharField(max_length=100)),
                ('engine_type', models.CharField(max_length=100)),
                ('engine_make', models.CharField(max_length=100)),
                ('engine_model', models.CharField(max_length=100)),
                ('engine_year', models.CharField(max_length=100)),
                ('power', models.CharField(max_length=100)),
                ('drive_type', models.CharField(max_length=100)),
                ('propeller_type', models.CharField(max_length=100)),
                ('folding_propeller', models.CharField(max_length=100)),
                ('engine_usage_hours', models.IntegerField()),
                ('certification', models.CharField(max_length=100)),
                ('cabins', models.IntegerField()),
                ('double_berths', models.IntegerField()),
                ('heads', models.IntegerField()),
                ('fuel_tanks', models.IntegerField()),
                ('fresh_water_tanks', models.IntegerField()),
                ('windlass', models.CharField(max_length=100)),
                ('boat_description', models.TextField(max_length=100000)),
                ('boat_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('boat_photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('boat_photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('boat_photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('boat_photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
