# Generated by Django 3.0.7 on 2022-01-03 14:47

import ckeditor.fields
from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='covers',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bimini Top', 'Bimini Top'), ('Spray hood', 'Spray hood')], max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='electrical_equipment',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Shore power inlet', 'Shore power inlet'), ('Generator', 'Generator'), ('Inverter', 'Inverter')], max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='electronics',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Depthsounder', 'Depthsounder'), ('Radar', 'Radar'), ('Log-speedometer', 'Log-speedometer'), ('Wind speed and direction', 'Wind speed and direction'), ('Repeater(s)', 'Repeater(s)'), ('TV set', 'TV set'), ('Navigation center', 'Navigation center')], max_length=96, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='inside_equipment',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Stern thruster', 'Stern thruster'), ('Dishwasher', 'Dishwasher'), ('Bow thruster', 'Bow thruster'), ('Electric bilge pump', 'Electric bilge pump'), ('Oven', 'Oven'), ('Manual bilge pump', 'Manual bilge pump'), ('Air compressor', 'Air compressor')], max_length=96, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='outside_equipment',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Teak cockpit', 'Teak cockpit'), ('Cockpit shower', 'Cockpit shower'), ('Teak sidedecks', 'Teak sidedecks'), ('Hydraulic gangway', 'Hydraulic gangway'), ('Radar reflector', 'Radar reflector'), ('Tender', 'Tender'), ('Cockpit cushions', 'Cockpit cushions')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='rigging',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Steering wheel', 'Steering wheel'), ('Electric winch', 'Electric winch')], max_length=29, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='sails',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Fully battened mainsail', 'Fully battened mainsail'), ('Gennaker/Cruising spinnaker', 'Gennaker/Cruising spinnaker'), ('Furling genoa', 'Furling genoa')], max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='boat_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
