# Generated by Django 3.0.7 on 2022-01-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0002_auto_20220103_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='boat_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
